version: '3.8'

services:
  kafka:
    container_name: turkcellkafka
    image: bashj79/kafka-kraft
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/opt/kafka/kafka-logs

  mongodb:
    container_name: turkcellfilterdb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  mongoinvoice:
    container_name: invoicedb
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongoinvoice_data:/data/db
volumes:
  kafka_data:
  mongodb_data:
  mongoinvoice_data: