
spring:
  application:
    name: INVENTORY-SERVICE
  datasource:
    username: postgres
    password: '12345'
    url: jdbc:postgresql://localhost:5432/inventorydbdev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    metadata-map:
      serviceId: inventory-service
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    prefer-ip-address: true
server:
  port: 0